In [6]:
import numpy as np

In [17]:
a = np.arange(10)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
a*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [10]:
b = np.array(['a','b','c'])
b

array(['a', 'b', 'c'], dtype='<U1')

In [11]:
b*2

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U1'), dtype('int32')) -> None

In [47]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
c*a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [19]:
d = np.arange(12)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
d = d.reshape(2,6)
d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [20]:
e = np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [24]:
d*e

array([[ 0,  1,  4,  9, 16, 25],
       [ 0,  7, 16, 27, 40, 55]])

In [25]:
d = d.ravel()

In [26]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
d>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True])

In [28]:
n = np.random.randint(1, 10, 8)
n

array([7, 3, 7, 6, 2, 1, 2, 4])

In [29]:
n.sum()

32

In [33]:
d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [37]:
d.ndim

2

In [38]:
d.sum(axis=1)

array([15, 51])

In [42]:
d.min(axis = 1)

array([0, 6])

In [43]:
d.max()

11

In [41]:
d.mean()

5.5

In [48]:
a = np.arange(10)

In [45]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.dot(a,c)

285

In [56]:
d = np.arange(1,5)
d = d.reshape(2, 2)

In [57]:
d

array([[1, 2],
       [3, 4]])

In [59]:
d**2

array([[ 1,  4],
       [ 9, 16]])

In [60]:
np.linalg.matrix_power(d,2)

array([[ 7, 10],
       [15, 22]])

3x+y = 7
2y-5x=3

In [62]:
k = np.array([[3,1],[-5,2]])
s = np.array([7, 3])
g = np.linalg.solve(k,s)

In [63]:
g.dtype

dtype('float64')