In [ ]:
$ pip install numpy

In [2]:
import numpy as np

In [4]:
mas = [['й', 'ц', 'у'], ['к','е','н'], ['г', 'ш', 'щ']] 
print(mas) 
print(mas[0][0]) 
print(mas[2][2]) 

[['й', 'ц', 'у'], ['к', 'е', 'н'], ['г', 'ш', 'щ']]
й
щ


In [5]:
mas*2

[['й', 'ц', 'у'],
 ['к', 'е', 'н'],
 ['г', 'ш', 'щ'],
 ['й', 'ц', 'у'],
 ['к', 'е', 'н'],
 ['г', 'ш', 'щ']]

In [2]:
a = 3           
mas = [0] * a 
for i in range(a): 
    mas[i] = [0] * a 
mas 

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]

In [1]:
a = 3
mas = [[2] * a for i in range(a)]
mas

[[2, 2, 2], [2, 2, 2], [2, 2, 2]]

In [8]:
mas = [[1, 1, 1], [1, 1, 1], [1, 1, 1]]
for i in range(len(mas)):
    for i2 in range(len(mas[i])):
        print(mas[i][i2], end=' ')
    print()

1*1*1*
1*1*1*
1*1*1*


In [7]:
mas = [[1, 1, 1], [1, 1, 1], [1, 1, 1]]
for i in mas:
    for j in i:
        print(j)
    print()

1
1
1

1
1
1

1
1
1



In [21]:
list_1 = [1, 2, 3]
print(list_1  *  2)

[1, 2, 3, 1, 2, 3]


In [22]:
type(list_1)

list

In [4]:
import numpy as np 

In [27]:
nums = np.array([2, 3, 4, 5, 6, False, 0.6, '2',[1, 2, 3]])
nums

C:\Users\tabul\AppData\Local\Temp\ipykernel_10740\13901354.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  nums = np.array([2, 3, 4, 5, 6, False, 0.6, '2',[1, 2, 3]])


array([2, 3, 4, 5, 6, False, 0.6, '2', list([1, 2, 3])], dtype=object)

In [26]:
type(nums) 

numpy.ndarray

In [28]:
nums.dtype

dtype('O')

In [42]:
nums = np.array([[[2,4,6], [8,10,12], [14,16,18]],[[2,4,6], [8,10,12], [14,16,18]]]) 
nums 

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]])

In [29]:
nums = np.array([(1, 2), [1,2]])
nums


array([[1, 2],
       [1, 2]])

In [34]:
nums = np.arange(1,17) 
nums

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [11]:
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [37]:
lin = np.linspace(1, 10)
lin

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [38]:
len(lin)

50

In [39]:
r = np.random.randint(50, 100, 5)
r

array([81, 87, 70, 56, 82])

In [41]:
import random
r = random.randrange(100)
r

20

In [43]:
nums.shape

(2, 3, 3)

In [44]:
n = np.arange(1,25)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [45]:
n.size

24

In [48]:
nums2 = n.reshape(3, 8) 
nums2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [49]:
nums2.size

24

In [51]:
nums.ndim

3